server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: Info@123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibertnate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

  output:
    ansi:
      enabled: ALWAYS

  logging:
    level:
      com.ead: TRACE
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate: INFO