server:
  port: 8082
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: Info@123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibertnate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

